version: "3"
services:
    redis:
        image: redis:alpine
        volumes:
            # https://github.com/docker-library/redis/blob/b6d413ceff3a2bca10a430ace121597fa8fe2a2c/5.0/alpine/Dockerfile#L73
            - pin-cache-data:/data
        networks:
            - pin-network
        expose:
            - "${REDIS_PORT}"
        command:
            # https://github.com/docker-library/redis/blob/b6d413ceff3a2bca10a430ace121597fa8fe2a2c/5.0/alpine/Dockerfile#L80
            - redis-server
            - "--requirepass ${REDIS_PASSWD}"
            - "--port ${REDIS_PORT}"
            - "--timeout ${REDIS_IDLE_CLIENT_TIMEOUT_SECONDS}"
            - "--maxclients ${REDIS_MAX_CLIENTS}"
            - "--maxmemory ${REDIS_MAXMEM_BYTES}"
            - "--maxmemory-policy ${REDIS_MAXMEM_POLICY}"
    server:
        build:
            # paths are relative to the location of compose file
            context: ..
            dockerfile: ./docker/server.DockerFile # NOTE relative to the context root
        depends_on: # NOTE only guarantee startup and termination order on container level, not on service level
            - redis
        environment:
            - PIN_VERBOSE
            - PIN_HOST
            - PIN_PORT
            - PIN_REQ_BODY_SIZE_MAX_BYTE
            - PIN_TITLE_SIZE_MAX_BYTE
            - PIN_NOTE_SIZE_MAX_BYTE
            - PIN_ATTACHMENT_SIZE_MAX_BYTE
            - PIN_ATTACHMENT_COUNT_MAX
            - REDIS_HOST
            - REDIS_PORT
            - REDIS_PASSWD
            - REDIS_DB
        networks:
            - pin-network
        # NOTE only expose frontend service to outside world
        # https://docs.docker.com/compose/compose-file/#ports
        # https://docs.docker.com/compose/compose-file/#expose
        ports:
            - "${PIN_HOST_PORT}:${PIN_PORT}"
    deleter:
        build:
            context: ..
            dockerfile: ./docker/deleter.DockerFile
        depends_on:
            - redis
        environment:
            - PIN_VERBOSE
            - REDIS_HOST
            - REDIS_PORT
            - REDIS_PASSWD
            - REDIS_DB
            - PIN_STORE_JUNK_FETCHER_POOL_SIZE
            - PIN_DELETER_LOCAL_CACHE_SIZE
            - PIN_DELETER_SWEEP_FREQ
            - PIN_DELETER_MAX_SWEEP_LOAD
            - PIN_DELETER_EXEC_POOL_SIZE
            - PIN_DELETER_WIP_CACHE_ENTRY_EXPIRY
        networks:
            - pin-network
networks:
    pin-network:
volumes:
    pin-cache-data:
